#!/bin/bash

# http://mywiki.wooledge.org/BashFAQ/028
if [[ $BASH_SOURCE = */* ]]; then
    DIR=${BASH_SOURCE%/*}/
else
    DIR=./
fi

java -Xmx256M -jar "$DIR/target/lab-1.0-SNAPSHOT-jar-with-dependencies.jar"