#!/bin/bash

# A small wrapper script for invoking the Maelstrom jar, with arguments.

exec java -Djava.awt.headless=true -jar "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/lib/maelstrom.jar" "$@"
