#!/usr/bin/env bash

# A small wrapper script for invoking the Maelstrom jar, with arguments.

THIS=`basename "$0"`

# Account for users who want to symlink this script into their PATH
SCRIPT_DIR=$(dirname $(realpath $THIS))

exec java -Djava.awt.headless=true -jar "${SCRIPT_DIR}/lib/maelstrom.jar" "$@"
